---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: aws

verifier:
  name: awspec

suites:
  - name: s3_bucket
    driver:
      name: terraform
      root_module_directory: terraform/s3_bucket
    verifier:
      patterns:
        - ./spec/s3_bucket_spec.rb
  - name: route53_zone
    driver:
      name: terraform
      root_module_directory: terraform/route53_zone
    verifier:
      patterns:
        - ./spec/route53_zone_spec.rb
  - name: acm_certificate
    driver:
      name: terraform
      root_module_directory: terraform/acm_certificate
    verifier:
      patterns:
        - ./spec/acm_certificate_spec.rb
  - name: cloudfront_distribution
    driver:
      name: terraform
      root_module_directory: terraform/cloudfront_distribution
      command_timeout: 1200
    verifier:
      patterns:
        - ./spec/cloudfront_distribution_spec.rb
