version: 2.1

commands:
  batect:
    description: "Run a task in batect"
    parameters:
      task:
        type: string
    steps:
      - checkout
      - run:
          command: ./batect << parameters.task >>

jobs:

  tflint:
    working_directory: ~/repo
    machine: true
    steps:
      - batect:
          task: terraform-tflint

  tf-local-apply:
    working_directory: ~/repo
    machine: true
    steps:
      - batect:
          task: terraform-local-apply

  tf-medium-test:
    working_directory: ~/repo
    machine: true
    steps:
      - batect:
          task: terraform-medium-test

  tf-apply-dev:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: dev
    steps:
      - batect:
          task: terraform-apply

  deploy-dev:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: dev
    steps:
      - batect:
          task: app-deploy

  tf-apply-prod:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: prod
    steps:
      - batect:
          task: terraform-apply

  deploy-prod:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: prod
    steps:
      - batect:
          task: app-deploy

workflows:
  version: 2
  scan-build-test-deploy:
    jobs:
      - tflint
      - tf-local-apply
      - tf-medium-test
      - tf-apply-dev:
          requires:
            - tflint
            - tf-local-apply
            - tf-medium-test
      - deploy-dev:
          requires:
            - tf-apply-dev
      - unblock:
          type: approval
          requires:
            - deploy-dev
          filters:
            branches:
              only: master
      - tf-apply-prod:
          requires:
            - unblock
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - tf-apply-prod
          filters:
            branches:
              only: master
