version: 2.1

commands:
  batect:
    description: "Run a task in batect"
    parameters:
      task:
        type: string
    steps:
      - checkout
      - run:
          command: ./batect << parameters.task >>
          no_output_timeout: 30m

jobs:

  tf-tflint:
    working_directory: ~/repo
    machine: true
    steps:
      - batect:
          task: terraform-tflint

  tf-local-apply:
    working_directory: ~/repo
    machine: true
    steps:
      - batect:
          task: terraform-local-apply

  tf-unit-test:
    working_directory: ~/repo
    machine: true
    steps:
      - batect:
          task: terraform-unit-test

  tf-apply-dev:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: dev
    steps:
      - batect:
          task: terraform-apply

  app-build-dev:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: dev
    steps:
      - batect:
          task: app-build

  app-deploy-dev:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: dev
    steps:
      - batect:
          task: app-deploy

  tf-apply-prod:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: prod
    steps:
      - batect:
          task: terraform-apply

  app-build-prod:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: prod
    steps:
      - batect:
          task: app-build

  app-deploy-prod:
    working_directory: ~/repo
    machine: true
    environment:
      ENVIRONMENT: prod
    steps:
      - batect:
          task: app-deploy

workflows:
  version: 2
  deploy:
    jobs:
      - tf-tflint
      - tf-local-apply
      - tf-unit-test
      - tf-apply-dev:
          requires:
            - tf-tflint
      - app-deploy-dev:
          requires:
            - tf-apply-dev
      - unblock:
          type: approval
          requires:
            - app-deploy-dev
          filters:
            branches:
              only: master
      - tf-apply-prod:
          requires:
            - unblock
          filters:
            branches:
              only: master
      - app-deploy-prod:
          requires:
            - tf-apply-prod
          filters:
            branches:
              only: master
